# This service is built from the Dockerfile in the current directory.
services:
  server:
    container_name: adeeb_hono_postgres
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    # Provide secrets for server
    # secrets:
    #   - jwt_private
    #   - jwt_public
    # environment:
      # Provide JWT private key file in ENVs to read with something like `fs` in node, like:
      # const JWT_PRIVATE = fs.readFileSync(process.env.JWT_PRIVATE_FILE).toString().trim()
      # JWT_PRIVATE_FILE: /run/secrets/jwt_private
      # JWT_PUBLIC_FILE: /run/secrets/jwt_public
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis

  db:
    # Container name is used as ${host} when connecting to database
    container_name: adeeb_postgres
    image: postgres:16.3-alpine
    restart: unless-stopped
    # Use db-data volume to persist Database on restarts
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: adeeb_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  redis:
    container_name: cache
    restart: unless-stopped
    image: valkey/valkey:7.2.5-bookworm
    command: valkey-server --loglevel warning
    ports:
      - 6379

volumes:
  db-data:
# secrets:
#   jwt_private:
#     file: ./jwtRSA256-private.pem
#   jwt_public:
#     file: ./jwtRSA256-public.pem
